######################################################################
#
#	Makefile for dgrep and test programs in Windows NT
#
######################################################################

dgrep:	dgrep.exe
try:	try.exe

WILDARG	= d:\msvc20\lib\setargv.obj

CC	= cl
CFLAGS	= -O2 -G5 -Gs -J -c -DECTYPE -W3 -DNT -DMSC -D_WIN32 -DWIN32 -I..\lib

LINK	= cl
LIBS	= -link ..\lib\cwnt.lib

DFAOBJ	= dfaregex.obj dfa.obj calcpos.obj dfatree.obj regmust.obj set.obj clib.obj
	  
DGREPOBJ = dgrep.obj bm.obj $(DFAOBJ)

dgrep.exe: $(DGREPOBJ)
	$(LINK) $(LFLAGS) $(DGREPOBJ) $(WILDARG) $(LIBS)

TRYOBJ = try.obj $(DFAOBJ)

try.exe: $(TRYOBJ)
	$(LINK) $(LFLAGS) $(TRYOBJ) $(LIBS)

.c.obj:
	$(CC) $(CFLAGS) $<

dfa.h:		set.h

dgrep.obj:	dgrep.c dfaregex.h dfa.h system.h
bm.obj:		bm.c dfa.h system.h
dfaregex.obj:	dfaregex.c dfaregex.h dfa.h system.h
dfa.obj:	dfa.c dfa.h system.h
calcpos.obj:	calcpos.c dfa.h system.h
dfatree.obj:	dfatree.c dfa.h system.h
regmust.obj:	regmust.c dfa.h system.h
set.obj:	set.c set.h system.h
clib.obj:	clib.c system.h
try.obj:	try.c dfaregex.h
