xabc	ABC	n	-	-
ABC	xbc	n	-	-
abc	AXC	n	-	-
ABC	abx	n	-	-
abc	XABCY	y	-	-
ABC	ababc	y	-	-
ab*c	ABC	y	-	-
AB*bc	abc	y	-	-
ab*bc	ABBC	y	-	-
AB*bc	abbbbc	y	-	-
ab+bc	ABBC	y	-	-
AB+bc	abc	n	-	-
ab+bc	ABQ	n	-	-
AB+bc	abbbbc	y	-	-
ab?bc	ABBC	y	-	-
AB?bc	abc	y	-	-
ab?bc	ABBBBC	n	-	-
AB?c	abc	y	-	-
^abc$	ABC	y	-	-
^ABC$	abcc	n	-	-
^abc	ABCC	y	-	-
^ABC$	aabc	n	-	-
abc$	AABC	y	-	-
^	ABC	y	-	-
$	ABC	y	-	-
^$		y	-	-
a.c	ABC	y	-	-
A.C	axc	y	-	-
a.*c	AXYZC	y	-	-
A.*C	axyzd	n	-	-
a[bc]d	ABC	n	-	-
A[BC]D	abd	y	-	-
a[b-d]e	ABD	n	-	-
A[B-D]E	ace	y	-	-
a[b-d]	AAC	y	-	-
A[-B]	a-	y	-	-
a[b-]	A-	y	-	-
A[B-A]	ab	y	-	-
a[]b	-	c	-	-
A[	-	c	-	-
a]	A]	y	-	-
A[\]]B	a]b	y	-	-
a[^bc]d	AED	y	-	-
A[^BC]D	abd	n	-	-
a[^-b]c	ADC	y	-	-
A[^-B]C	a-c	n	-	-
a[^]b]c	A]c	n	-	-
A[^]B]C	adc	y	-	-
ab|cd	ABC	y	-	-
AB|CD	abcd	y	-	-
()ef	DEF	y	-	-
()*	*	c	-	-
*a	*A	y	-	-
^*	*	y	-	-
$*	A	y	-	-
(*)B	-	c	-	-
$b	B	n	-	-
A\	a\	y	-	-
a\(b	A(b	y	-	-
A\(*B	ab	y	-	-
a\(*b	A((b	y	-	-
A\\B	a\b	y	-	-
abc)	-	c	-	-
(ABC	-	c	-	-
((a))	ABC	y	-	-
(A)B(C)	abc	y	-	-
a+b+c	AABBABC	y	-	-
A**	-	c	-	-
a*?	-	c	-	-
(A*)*		y	-	-
(a*)+	A	y	-	-
(A|)*		y	-	-
(a*|b)*	B	y	-	-
(A+|B)*	ab	y	-	-
(a+|b)+	AB	y	-	-
(A+|B)?	ab	y	-	-
[^ab]*	CDE	y	-	-
^[AB]+	ab	y	-	-
^[ab]+	CB	n	-	-
(^)*	c	y	-	-
(ab|)*	AB	y	-	-
)(	-	c	-	-
	ABC	y	-	-
ABC		n	-	-
a*		y	-	-
([ABC])*D	abbbcd	y	-	-
([abc])*bcd	ABCD	y	-	-
A|b|C|d|E	e	y	-	-
(a|b|c|d|e)f	EF	y	-	-
((a*|B))*	b	y	-	-
((a*|b))*	BBBBB	y	-	-
((A*|b))*		y	-	-
abcd*efg	ABCDEFG	y	-	-
AB*	xabyabbbz	y	-	-
ab*	XAYABBBZ	y	-	-
(AB|cd)E	abcde	y	-	-
[abhgefdc]ij	HIJ	y	-	-
^(ab|CD)e	abcde	n	-	-
(abc|)ef	ABCDEF	y	-	-
(A|B)c*D	abcd	y	-	-
(ab|ab*)bc	ABC	y	-	-
A([BC]*)C*	abc	y	-	-
a([bc]*)(c*d)	ABCD	y	-	-
A([BC]+)(C*D)	abcd	y	-	-
a([bc]*)(c+d)	ABCD	y	-	-
A[BCD]*DCDCDE	adcdcde	y	-	-
a[bcd]+dcdcde	ADCDCDE	n	-	-
(AB|a)B*C	abc	y	-	-
((a)(b)c)(d)	ABCD	y	-	-
[A-ZA-Z_][A-ZA-Z0-9_]*	alpha	y	-	-
^a(bc+|b[eh])g|.h$	ABH	y	-	-
(BC+D$|EF*G.|H?I(J|K))	effgz	y	-	-
(BC+D$|EF*G.|H?I(J|K))	IJ	y	-	-
(bc+d$|ef*g.|h?i(j|k))	effg	n	-	-
(bc+d$|ef*g.|h?i(j|k))	BCDD	n	-	-
(BC+D$|EF*G.|H?I(J|K))	bccd	y	-	-
(bc+d$|ef*g.|h?i(j|k))	REFFGZ	y	-	-
((((((((((A))))))))))	a	y	-	-
(((((((((a)))))))))	B	n	-	-
MULTIPLE WORDS OF TEXT	uh-uh	n	-	-
multiple words	MULTIPLE WORDS, YEAH	y	-	-
(.*)C(.*)	abcde	y	-	-
\((.*), (.*)\)	(a, B)	y	-	-
[K]	ab	n	-	-
abcd	ABCD	y	-	-
A(BC)D	abcd	y	-	-
a[-]?c	AC	y	-	-
.$	abc	y	-	-
(A|B)*A(A|B)(A|B)(A|B)(A|B)(A|B)(A|B)(A|B)(A|B)(A|B)(A|B)$	ababababaabbbbbbbbbb	y	-	-
(A|B)*A(A|B)(A|B)(A|B)(A|B)(A|B)(A|B)(A|B)(A|B)(A|B)(A|B)$	abababababaaaaaaaaaa	n	-	-
(a|b)*a(a|b)(a|b)(a|b)(a|b)(a|b)(a|b)(a|b)(a|b)(a|b)(a|b)$	ABABABABAABBBBBBBBBB	y	-	-
(a|b)*a(a|b)(a|b)(a|b)(a|b)(a|b)(a|b)(a|b)(a|b)(a|b)(a|b)$	ABABABABABAAAAAAAAAA	n	-	-
