ren adapter.c adapter.c
ren alloca.h alloca.h
ren assert.c assert.c
ren bak.bat bak.bat
ren c.h c.h
ren cputs.c cputs.c
ren diruti.c diruti.c
ren diruti.h diruti.h
ren dirutior.c dirutior.c
ren diskfree.c diskfree.c
ren dosvio.c dosvio.c
ren ectype.c ectype.c
ren ectype.h ectype.h
ren filelist.c filelist.c
ren filelist.h filelist.h
ren getch.c getch.c
ren getche.c getche.c
ren getopt.c getopt.c
ren getopt.h getopt.h
ren glob.c glob.c
ren kbd.c kbd.c
ren kbd.h kbd.h
ren lassert.h lassert.h
ren lib.zip lib.zip
ren listmenu.c listmenu.c
ren listmenu.h listmenu.h
ren lrand.c lrand.c
ren lrand.h lrand.h
ren makefile makefile
ren os2vio.c os2vio.c
ren putch.c putch.c
ren rbtree.c rbtree.c
ren rbtree.h rbtree.h
ren read_me read_me
ren rest.bat rest.bat
ren setargv.c setargv.c
ren splitpat.c splitpat.c
ren timer.c timer.c
ren timer.h timer.h
ren tmp.bat tmp.bat
ren tmp.c tmp.c
ren ultoa.c ultoa.c
ren utime.c utime.c
ren utime.h utime.h
ren vio.h vio.h