/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header: /usr/fsys/odin/a/vern/flex/RCS/flex.skel,v 2.13 90/05/26 17:24:13 vern Exp $
 */

#define FLEX_SCANNER

#include <stdio.h>

#ifdef __STDC__

#ifndef DONT_HAVE_STDLIB_H
#include <stdlib.h>
#else
void *malloc( unsigned );
void free( void* );
#endif

#define YY_USE_PROTOS
#define YY_USE_CONST
#endif


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#ifndef __STDC__
#include <stdlib.h>
#endif

#include <osfcn.h>

/* use prototypes in function declarations */
#define YY_USE_PROTOS

/* the "const" storage-class-modifier is valid */
#define YY_USE_CONST

#endif


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#define const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yytext, yyleng, 1, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 * 	if ( something_happens )
 *		YY_FATAL_ERROR( "oops, the something happened" );
 *	else
 *		everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, stderr ); \
		(void) putc( '\n', stderr ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
	do \
		{ \
		yy_init_buffer( yy_current_buffer, yyin ); \
		yy_load_buffer_state(); \
		} \
	while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void ))

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR unsigned char
#define INITIAL 0
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cover.h"
#include "cover_ta.h"

#define FLEX

void count(void);
static void count_output(void);

int  cover_c_mode = 1;
int  cover_all = 0;
char last_identifier[MAXLINE];
char last_typename[MAXLINE];


/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yytext */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;		/* input buffer */
    YY_CHAR *yy_buf_pos;	/* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters*/
    int yy_buf_size;

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;		/* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

#define YY_END_OF_BUFFER 153
typedef int yy_state_type;
static const short int yy_accept[532] =
    {   0,
        0,    0,  153,  151,  149,  150,  137,  151,   92,  143,
      136,  151,  131,  132,  141,  140,  128,  139,  135,  142,
       95,   96,  129,  125,  144,  130,  145,  148,   93,   93,
      133,  134,  146,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,  126,  147,  127,  138,  124,    0,  102,    0,
       92,  110,  119,  111,    0,    0,  108,  116,  106,  117,
      107,  118,    0,  100,    1,  109,  101,   95,   96,    0,
       95,    0,   96,  115,  121,  123,  122,  114,   93,    0,
        0,    0,  112,   93,   93,   93,   93,   93,   93,   93,

       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,    9,
       93,   93,   93,   93,   93,   93,   93,   93,   17,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,  113,  120,   97,  103,    0,  100,
        0,  101,    0,   99,   94,  105,  104,    0,   91,    0,
        0,    0,    0,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,

       93,   93,   93,   93,   93,   93,   93,   93,   42,   93,
       15,   93,   93,   18,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,    0,  100,    0,  101,   99,   94,   98,
        0,    0,    0,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   52,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,    2,
       93,    4,   93,    5,   93,   93,   93,   93,   93,   93,
       11,   12,   93,   93,   16,   44,   93,   23,   93,   43,

       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   36,   93,   93,   90,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   53,
       93,   93,   93,   93,   93,   93,   93,   79,    0,    0,
       93,   93,   93,   93,   93,   93,   57,   93,   93,   62,
       93,   93,   93,   69,   93,   93,    3,   39,    6,   93,
       93,   93,   93,   93,   93,   14,   93,   93,   84,   93,
       93,   93,   27,   93,   93,   93,   93,   93,   93,   93,
       34,   93,   93,   38,   93,   93,   72,   93,   93,   78,
       93,    0,    0,   93,   93,   93,   93,   93,   93,   93,

       93,   93,   93,   19,   93,   63,   93,   93,   93,    0,
       89,   45,   47,   93,   71,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   10,   13,
       93,   93,   40,   93,   26,   28,   29,   30,   31,   32,
       83,   93,   93,   93,   93,   50,   93,   65,   82,    0,
       88,   46,   48,   93,   93,   73,   93,   93,   20,   21,
       22,   93,   93,   93,   93,   49,   93,   93,   93,   61,
       64,   93,   93,   93,   93,   93,    8,   93,   93,   93,
       93,   93,   33,   93,   93,   81,   80,   93,   51,   93,
       60,   93,   66,   93,   93,   93,   56,   93,   93,   68,

       74,   76,    7,   93,   93,   93,   24,   25,   35,   37,
       93,   93,   93,   75,   77,   54,   93,   67,   86,   85,
       41,   93,   55,   93,   58,    0,    0,   59,    0,   87,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   25,   27,   28,   29,   30,   31,
       32,   33,   34,    1,   35,   36,   35,   35,   37,   38,
       39,   39,   39,   39,   39,   40,   39,   39,   41,   42,
       39,   39,   43,   39,   44,   39,   39,   45,   39,   39,
       46,   47,   48,   49,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   39,   60,   61,   62,   63,
       64,   65,   39,   66,   67,   68,   69,   70,   71,   72,
       73,   74,   75,   76,   77,   78,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[79] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        1,    1,    1,    1,    5,    5,    6,    4,    7,    8,
        7,    7,    7,    7,    7,    1,    1,    1,    1,    7,
        5,    5,    5,    5,    6,    4,    7,    7,    7,    7,
        8,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    1,    1,    1,    1
    } ;

static const short int yy_base[547] =
    {   0,
        0,    0,  786,  787,  787,  787,  753,   72,    0,  752,
       70,  736,  787,  787,  750,   66,  787,   67,   65,   80,
      102,  157,  787,  787,   64,  749,   71,  787,    0,   94,
      787,  787,  748,  191,  710,  712,   57,   52,   71,   80,
      713,  707,   54,  711,   63,  723,  718,   77,   24,  709,
      707,  712,  787,   77,  787,  787,  787,  126,  787,    0,
        0,  787,  787,  787,  129,  147,  787,  787,  787,  787,
      787,  787,  751,  132,  787,  787,  152,   92,    0,  240,
      155,    0,  156,  736,  787,  787,  787,  735,    0,  144,
      719,  758,  787,  695,  691,  711,  696,  709,   83,  218,

      692,  707,  703,  684,   98,  686,  691,  689,  697,  700,
      147,  682,  694,  681,  692,  695,  682,  688,  682,  673,
      674,  671,  671,  672,  673,  670,  667,  677,    0,  665,
      669,  671,  679,  662,   97,  664,  129,  101,  668,  660,
      660,  101,  100,  665,  787,  787,  787,  787,  271,  787,
      285,  787,  294,  285,  170,  787,  787,  159,  787,    0,
      193,  208,  198,  664,  657,  655,  652,  652,  661,  650,
      649,  664,  660,  658,  640,  660,  647,  654,  657,  162,
      681,  644,  638,  649,  638,  155,  636,  644,  632,  648,
      647,  630,  626,  218,  641,  627,  629,  641,  636,  637,

      623,  169,  637,  221,  635,  631,  623,  629,    0,  632,
        0,  618,  626,  625,  622,  623,  611,  623,  616,  605,
      607,  609,  616,  602,  600,  600,  612,  611,  601,  605,
      609,  611,  600,  306,  297,  339,  312,  787,  311,  787,
      231,  647,    0,  598,  594,  636,  595,  602,  633,  585,
      590,  584,  595,  596,  583,  237,  275,  596,  579,  591,
      577,  619,  337,  587,  588,  576,  618,  570,  569,  581,
      580,  580,  567,  579,  576,  567,  573,  575,  574,    0,
      566,    0,  564,    0,  556,  564,  553,  549,  558,  558,
        0,    0,  552,  549,    0,    0,  550,  554,  560,    0,

      562,  545,  545,  542,  554,  544,  548,  553,  552,  553,
      549,  539,  544,    0,  532,  544,  787,  530,  531,  570,
      536,  543,  567,  537,  342,  536,  537,  528,  524,  566,
      518,  526,  348,  518,  530,  529,  528,    0,  374,  503,
      525,  517,  511,  550,  522,  508,    0,  507,  518,    0,
      520,  504,  518,    0,  517,  516,    0,    0,    0,  503,
      504,  499,  498,  507,  498,    0,  494,  495,    0,  497,
      489,  493,    0,  501,  492,  476,  460,  469,  470,  468,
        0,  459,  452,    0,  451,  441,    0,  439,  426,    0,
      423,  379,  396,  410,  392,  385,  385,  424,  395,  384,

      420,  423,  420,    0,  377,    0,  391,  390,  389,  362,
      787,    0,    0,  370,    0,  386,  385,  369,  367,  372,
      377,  369,  369,  368,  359,  359,  362,  361,    0,    0,
      355,  360,    0,  367,    0,    0,    0,    0,    0,    0,
        0,  365,  365,  358,  355,    0,  356,    0,    0,  338,
      787,    0,    0,  349,  345,    0,  360,  355,    0,    0,
        0,  343,  347,  346,  345,    0,  344,  341,  333,    0,
        0,  344,  345,  337,  336,  341,    0,  328,  327,  326,
      330,  317,    0,  324,  315,    0,    0,  302,    0,  295,
        0,  285,    0,  288,  287,  277,    0,  259,  234,    0,

        0,    0,    0,  222,  219,  216,    0,    0,    0,    0,
      229,  198,  188,    0,    0,    0,  183,    0,    0,    0,
        0,  383,    0,  180,    0,  387,  210,    0,  196,  142,
      787,  454,  462,  470,  475,  480,  485,  491,  499,  504,
      512,  517,  522,  530,  538,  546
    } ;

static const short int yy_def[547] =
    {   0,
      531,    1,  531,  531,  531,  531,  531,  532,  533,  531,
      531,  534,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  535,  535,
      531,  531,  531,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  531,  531,  531,  531,  531,  532,  531,  532,
      533,  531,  531,  531,  534,  534,  531,  531,  531,  531,
      531,  531,  531,  536,  531,  531,  536,   21,   22,  531,
      531,  537,  531,  531,  531,  531,  531,  531,  535,  538,
      539,  531,  531,  535,  535,  535,  535,  535,  535,  535,

      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  540,  537,  531,  531,  538,  531,  538,
      539,  539,  541,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,

      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  531,  542,  531,  543,  531,  531,  531,
      541,  531,  541,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,

      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  531,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  531,  544,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  531,  545,  535,  535,  535,  535,  535,  535,  535,

      535,  535,  535,  535,  535,  535,  535,  535,  535,  544,
      531,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  545,
      531,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,

      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  531,  546,  535,  546,  546,
        0,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531
    } ;

static const short int yy_nxt[866] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   22,   22,   22,   22,   22,   22,   22,   23,   24,
       25,   26,   27,   28,   29,   29,   29,   29,   29,   30,
       29,   29,   29,   29,   29,   31,    4,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   29,
       44,   29,   45,   29,   46,   47,   48,   49,   50,   51,
       52,   29,   29,   29,   53,   54,   55,   56,   59,   63,
       68,  140,   73,   70,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   75,   84,   85,  141,   69,   71,   72,

       90,   64,   87,   88,   91,   92,  118,  114,  145,  129,
      115,   76,  119,  132,  116,  120,  130,  133,   60,   77,
      117,   78,   78,   78,   78,   78,   78,   78,   79,   79,
      124,  121,   59,  122,  136,  137,  531,  169,   80,  147,
      125,   81,  123,  126,  138,   81,   82,  139,  186,  531,
      159,  224,  146,  219,  530,  170,   80,   65,  231,  229,
      232,  187,   81,  531,  220,  159,  225,  230,  149,  150,
       81,  150,   60,   82,   77,   66,   79,   79,   79,   79,
       79,   79,   79,   79,   79,  222,  149,  150,  151,  152,
      160,  152,  150,   80,   81,   83,   83,  193,   81,   83,

       83,  194,  223,  240,  242,  160,  151,  152,  530,  239,
      531,   80,  152,  239,  195,   81,   83,   83,  161,  196,
      267,  268,  530,   81,   83,   83,   94,   95,   96,  260,
      239,   97,   98,   99,  261,  285,  286,  242,  239,  162,
      100,  101,  102,  103,  243,  104,  105,  528,  106,  107,
      525,  108,  524,  109,  153,  110,  153,  111,  523,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  171,  172,
      173,  174,  175,  176,  276,  288,  177,  243,  277,  289,
      178,  522,  179,  521,  180,  234,  520,  234,  181,  519,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  236,

      518,  236,  330,  331,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  238,  517,  238,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  150,  332,  150,  516,  339,  339,
      238,  339,  333,  392,  392,  238,  392,  515,  514,  152,
      239,  152,  150,  513,  239,  512,  511,  150,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  152,  401,  510,
      402,  239,  152,  403,  404,  339,  339,  509,  339,  239,
      392,  392,  508,  392,  526,  526,  507,  526,  526,  526,
      506,  526,  505,  504,  527,  503,  502,  501,  527,  500,

      499,  498,  405,  497,  496,  495,  494,  493,  492,  491,
      490,  340,  489,  488,  451,  487,  393,  486,  485,  484,
      483,  482,  481,  480,  479,  478,  477,  476,  475,  474,
      473,  472,  471,  470,  469,  468,  467,  466,  411,  465,
      464,  463,  462,  461,  460,  459,  458,  457,  340,  456,
      455,  454,  453,  393,   58,   58,   58,   58,   58,   58,
       58,   58,   61,  452,   61,   61,   61,   61,   61,   61,
       65,   65,  451,   65,   65,   65,   65,   65,   89,   89,
       89,   89,   89,   74,  449,   74,  448,   74,  155,  155,
      155,  158,  158,  158,  158,  158,  158,  158,  158,  161,

      161,  447,  161,  161,  161,  161,  161,  154,  446,  445,
      444,  154,  241,  241,  241,  241,  241,  241,  241,  241,
      235,  443,  442,  441,  235,  237,  440,  439,  438,  237,
      410,  410,  410,  410,  410,  410,  410,  410,  450,  450,
      450,  450,  450,  450,  450,  450,  529,  437,  529,  529,
      529,  529,  529,  529,  436,  435,  434,  433,  432,  431,
      430,  429,  428,  427,  426,  425,  424,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  414,  413,  412,  411,
      409,  408,  407,  406,  400,  399,  398,  397,  396,  395,
      394,  391,  390,  389,  388,  387,  386,  385,  384,  383,

      382,  381,  380,  379,  378,  377,  376,  375,  374,  373,
      372,  371,  370,  369,  368,  367,  366,  365,  364,  363,
      362,  361,  360,  359,  358,  357,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  347,  346,  345,  344,  343,
      342,  341,  338,  337,  336,  335,  334,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  319,  318,  317,
      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  287,  284,  283,
      282,  281,  280,  279,  278,  275,  274,  273,  272,  271,

      270,  269,  266,  265,  264,  263,  262,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  233,  228,  227,  226,  221,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      192,  191,  190,  189,  188,  185,  184,  183,  182,  168,
      167,  166,  165,  164,  163,  162,  157,  156,  148,  144,
      143,  142,  135,  134,  131,  128,  127,  113,  112,   93,
       86,   67,   66,   62,   57,  531,    3,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,

      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531
    } ;

static const short int yy_chk[866] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    8,   11,
       16,   49,   19,   18,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   20,   25,   25,   49,   16,   18,   18,

       30,   11,   27,   27,   30,   30,   38,   37,   54,   43,
       37,   20,   38,   45,   37,   38,   43,   45,    8,   21,
       37,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       40,   39,   58,   39,   48,   48,   78,   99,   21,   65,
       40,   21,   39,   40,   48,   21,   21,   48,  105,   66,
       90,  138,   54,  135,  530,   99,   21,   66,  143,  142,
      143,  105,   21,   78,  135,  158,  138,  142,   74,   74,
       21,   74,   58,   21,   22,   65,   22,   22,   22,   22,
       22,   22,   22,   22,   22,  137,   74,   74,   77,   77,
       90,   77,   74,   22,   81,   83,   22,  111,   81,   83,

       22,  111,  137,  161,  163,  158,   77,   77,  529,  155,
      162,   22,   77,  155,  111,   81,   83,   22,  162,  111,
      186,  186,  527,   81,   83,   22,   34,   34,   34,  180,
      155,   34,   34,   34,  180,  202,  202,  241,  155,  161,
       34,   34,   34,   34,  163,   34,   34,  524,   34,   34,
      517,   34,  513,   34,   80,   34,   80,   34,  512,   80,
       80,   80,   80,   80,   80,   80,   80,   80,  100,  100,
      100,  100,  100,  100,  194,  204,  100,  241,  194,  204,
      100,  511,  100,  506,  100,  149,  505,  149,  100,  504,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  151,

      499,  151,  256,  256,  151,  151,  151,  151,  151,  151,
      151,  151,  151,  153,  153,  153,  153,  153,  153,  153,
      153,  153,  154,  498,  154,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  235,  257,  235,  496,  263,  263,
      154,  263,  257,  325,  325,  154,  325,  495,  494,  237,
      239,  237,  235,  492,  239,  490,  488,  235,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  237,  333,  485,
      333,  239,  237,  333,  333,  339,  339,  484,  339,  239,
      392,  392,  482,  392,  522,  522,  481,  522,  526,  526,
      480,  526,  479,  478,  522,  476,  475,  474,  526,  473,

      472,  469,  333,  468,  467,  465,  464,  463,  462,  458,
      457,  263,  455,  454,  450,  447,  325,  445,  444,  443,
      442,  434,  432,  431,  428,  427,  426,  425,  424,  423,
      422,  421,  420,  419,  418,  417,  416,  414,  410,  409,
      408,  407,  405,  403,  402,  401,  400,  399,  339,  398,
      397,  396,  395,  392,  532,  532,  532,  532,  532,  532,
      532,  532,  533,  394,  533,  533,  533,  533,  533,  533,
      534,  534,  393,  534,  534,  534,  534,  534,  535,  535,
      535,  535,  535,  536,  391,  536,  389,  536,  537,  537,
      537,  538,  538,  538,  538,  538,  538,  538,  538,  539,

      539,  388,  539,  539,  539,  539,  539,  540,  386,  385,
      383,  540,  541,  541,  541,  541,  541,  541,  541,  541,
      542,  382,  380,  379,  542,  543,  378,  377,  376,  543,
      544,  544,  544,  544,  544,  544,  544,  544,  545,  545,
      545,  545,  545,  545,  545,  545,  546,  375,  546,  546,
      546,  546,  546,  546,  374,  372,  371,  370,  368,  367,
      365,  364,  363,  362,  361,  360,  356,  355,  353,  352,
      351,  349,  348,  346,  345,  344,  343,  342,  341,  340,
      337,  336,  335,  334,  332,  331,  330,  329,  328,  327,
      326,  324,  323,  322,  321,  320,  319,  318,  316,  315,

      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  299,  298,  297,  294,  293,  290,  289,
      288,  287,  286,  285,  283,  281,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  262,  261,  260,  259,  258,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  242,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  210,  208,  207,  206,  205,  203,  201,  200,
      199,  198,  197,  196,  195,  193,  192,  191,  190,  189,

      188,  187,  185,  184,  183,  182,  181,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  144,  141,  140,  139,  136,  134,  133,
      132,  131,  130,  128,  127,  126,  125,  124,  123,  122,
      121,  120,  119,  118,  117,  116,  115,  114,  113,  112,
      110,  109,  108,  107,  106,  104,  103,  102,  101,   98,
       97,   96,   95,   94,   92,   91,   88,   84,   73,   52,
       51,   50,   47,   46,   44,   42,   41,   36,   35,   33,
       26,   15,   12,   10,    7,    3,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,

      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp, *yy_bp;
    register int yy_act;



    if ( yy_init )
	{
	YY_USER_INIT;

	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

	if ( yy_current_buffer )
	    yy_init_buffer( yy_current_buffer, yyin );
	else
	    yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_load_buffer_state();

	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 532 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 531 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

yy_find_action:
	yy_act = yy_accept[yy_current_state];

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:	/* this label is used only to access EOF actions */


	switch ( yy_act )
	    {
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
{ comment(); }
	YY_BREAK
case 2:
{ count_output(); if (cover_all) return(AUTO); }
	YY_BREAK
case 3:
{ count_output(); if (cover_all) return(BREAK); }
	YY_BREAK
case 4:
{ count_output(); if (cover_all) return(CASE); }
	YY_BREAK
case 5:
{ count_output(); if (cover_all) return(CHAR); }
	YY_BREAK
case 6:
{ count_output(); if (cover_all) return(CONST); }
	YY_BREAK
case 7:
{ count_output(); if (cover_all) return(CONTINUE); }
	YY_BREAK
case 8:
{ count_output(); if (cover_all) return(DEFAULT); }
	YY_BREAK
case 9:
{ count_output(); if (cover_all) return(DO); }
	YY_BREAK
case 10:
{ count_output(); if (cover_all) return(DOUBLE); }
	YY_BREAK
case 11:
{ count_output(); if (cover_all) return(ELSE); }
	YY_BREAK
case 12:
{ count_output(); if (cover_all) return(ENUM); }
	YY_BREAK
case 13:
{ count_output(); if (cover_all) return(EXTERN); }
	YY_BREAK
case 14:
{ count_output(); if (cover_all) return(FLOAT); }
	YY_BREAK
case 15:
{ count_output(); if (cover_all) return(FOR); }
	YY_BREAK
case 16:
{ count_output(); if (cover_all) return(GOTO); }
	YY_BREAK
case 17:
{ count_output(); if (cover_all) return(IF); }
	YY_BREAK
case 18:
{ count_output(); if (cover_all) return(INT); }
	YY_BREAK
case 19:
{ count_output(); if (cover_all) return(INT8); }
	YY_BREAK
case 20:
{ count_output(); if (cover_all) return(INT16); }
	YY_BREAK
case 21:
{ count_output(); if (cover_all) return(INT32); }
	YY_BREAK
case 22:
{ count_output(); if (cover_all) return(INT64); }
	YY_BREAK
case 23:
{ count_output(); if (cover_all) return(LONG); }
	YY_BREAK
case 24:
{ count_output(); if (cover_all) return(LONGLONG); }
	YY_BREAK
case 25:
{ count_output(); if (cover_all) return(REGISTER); }
	YY_BREAK
case 26:
{ count_output(); if (cover_all) return(RETURN); }
	YY_BREAK
case 27:
{ count_output(); if (cover_all) return(SHORT); }
	YY_BREAK
case 28:
{ count_output(); if (cover_all) return(SIGNED); }
	YY_BREAK
case 29:
{ count_output(); if (cover_all) return(SIZEOF); }
	YY_BREAK
case 30:
{ count_output(); if (cover_all) return(STATIC); }
	YY_BREAK
case 31:
{ count_output(); if (cover_all) return(STRUCT); }
	YY_BREAK
case 32:
{ count_output(); if (cover_all) return(SWITCH); }
	YY_BREAK
case 33:
{ count(); cover_all = 1; return(TYPEDEF); }
	YY_BREAK
case 34:
{ count_output(); if (cover_all) return(UNION); }
	YY_BREAK
case 35:
{ count_output(); if (cover_all) return(UNSIGNED); }
	YY_BREAK
case 36:
{ count_output(); if (cover_all) return(VOID); }
	YY_BREAK
case 37:
{ count_output(); if (cover_all) return(VOLATILE); }
	YY_BREAK
case 38:
{ count_output(); if (cover_all) return(WHILE); }
	YY_BREAK
case 39:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 40:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 41:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 42:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 43:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 44:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 45:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 46:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 47:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 48:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 49:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 50:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 51:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 52:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 53:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 54:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 55:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 56:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 57:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 58:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 59:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 60:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 61:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 62:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 63:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 64:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 65:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 66:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 67:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 68:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 69:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 70:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 71:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 72:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 73:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 74:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 75:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 76:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 77:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 78:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 79:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 80:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 81:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 82:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 83:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 84:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 85:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 86:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 87:
{ count_output(); if (cover_all) return(MODIFIER); }
	YY_BREAK
case 88:
{ count_output(); if (cover_all) return(ASM); }
	YY_BREAK
case 89:
{ count_output(); if (cover_all) return(ASM); }
	YY_BREAK
case 90:
{ count_output(); if (cover_all) return(STRING_LITERAL); }
	YY_BREAK
case 91:
{ count_output(); if (cover_all) return(STRING_LITERAL); }
	YY_BREAK
case 92:
{ count(); 
                          if (strstr(yytext, ".c") != NULL) {
                              cover_c_mode = 1;
                              cover_all = 1;
                          } else if (strstr(yytext, ".h") != NULL) {
                              cover_c_mode = 0;
                          }
                        }
	YY_BREAK
case 93:
{ count_output(); 
                          if (is_type_name(yytext)) {
                              strcpy(last_typename, yytext);
			      if (cover_all) {
                                  return(TYPE_NAME);
                              }
                          } else {
                              strcpy(last_identifier, yytext);
			      if (cover_all) {
                                  return(IDENTIFIER);
                              }
                          }
			}
	YY_BREAK
case 94:
{ count_output(); if (cover_all) return(CONSTANT); }
	YY_BREAK
case 95:
{ count_output(); if (cover_all) return(CONSTANT); }
	YY_BREAK
case 96:
{ count_output(); if (cover_all) return(CONSTANT); }
	YY_BREAK
case 97:
{ count_output(); if (cover_all) return(CONSTANT); }
	YY_BREAK
case 98:
{ count_output(); if (cover_all) return(CONSTANT); }
	YY_BREAK
case 99:
{ count_output(); if (cover_all) return(CONSTANT); }
	YY_BREAK
case 100:
{ count_output(); if (cover_all) return(CONSTANT); }
	YY_BREAK
case 101:
{ count_output(); if (cover_all) return(CONSTANT); }
	YY_BREAK
case 102:
{ count_output(); if (cover_all) return(STRING_LITERAL); }
	YY_BREAK
case 103:
{ count_output(); if (cover_all) return(ELIPSIS); }
	YY_BREAK
case 104:
{ count_output(); if (cover_all) return(RIGHT_ASSIGN); }
	YY_BREAK
case 105:
{ count_output(); if (cover_all) return(LEFT_ASSIGN); }
	YY_BREAK
case 106:
{ count_output(); if (cover_all) return(ADD_ASSIGN); }
	YY_BREAK
case 107:
{ count_output(); if (cover_all) return(SUB_ASSIGN); }
	YY_BREAK
case 108:
{ count_output(); if (cover_all) return(MUL_ASSIGN); }
	YY_BREAK
case 109:
{ count_output(); if (cover_all) return(DIV_ASSIGN); }
	YY_BREAK
case 110:
{ count_output(); if (cover_all) return(MOD_ASSIGN); }
	YY_BREAK
case 111:
{ count_output(); if (cover_all) return(AND_ASSIGN); }
	YY_BREAK
case 112:
{ count_output(); if (cover_all) return(XOR_ASSIGN); }
	YY_BREAK
case 113:
{ count_output(); if (cover_all) return(OR_ASSIGN); }
	YY_BREAK
case 114:
{ count_output(); if (cover_all) return(RIGHT_OP); }
	YY_BREAK
case 115:
{ count_output(); if (cover_all) return(LEFT_OP); }
	YY_BREAK
case 116:
{ count_output(); if (cover_all) return(INC_OP); }
	YY_BREAK
case 117:
{ count_output(); if (cover_all) return(DEC_OP); }
	YY_BREAK
case 118:
{ count_output(); if (cover_all) return(PTR_OP); }
	YY_BREAK
case 119:
{ count_output(); if (cover_all) return(AND_OP); }
	YY_BREAK
case 120:
{ count_output(); if (cover_all) return(OR_OP); }
	YY_BREAK
case 121:
{ count_output(); if (cover_all) return(LE_OP); }
	YY_BREAK
case 122:
{ count_output(); if (cover_all) return(GE_OP); }
	YY_BREAK
case 123:
{ count_output(); if (cover_all) return(EQ_OP); }
	YY_BREAK
case 124:
{ count_output(); if (cover_all) return(NE_OP); }
	YY_BREAK
case 125:
{ count_output(); if (cover_all) return(';'); }
	YY_BREAK
case 126:
{ count_output(); if (cover_all) return('{'); }
	YY_BREAK
case 127:
{ count_output(); if (cover_all) return('}'); }
	YY_BREAK
case 128:
{ count_output(); if (cover_all) return(','); }
	YY_BREAK
case 129:
{ count_output(); if (cover_all) return(':'); }
	YY_BREAK
case 130:
{ count_output(); if (cover_all) return('='); }
	YY_BREAK
case 131:
{ count_output(); if (cover_all) return('('); }
	YY_BREAK
case 132:
{ count_output(); if (cover_all) return(')'); }
	YY_BREAK
case 133:
{ count_output(); if (cover_all) return('['); }
	YY_BREAK
case 134:
{ count_output(); if (cover_all) return(']'); }
	YY_BREAK
case 135:
{ count_output(); if (cover_all) return('.'); }
	YY_BREAK
case 136:
{ count_output(); if (cover_all) return('&'); }
	YY_BREAK
case 137:
{ count_output(); if (cover_all) return('!'); }
	YY_BREAK
case 138:
{ count_output(); if (cover_all) return('~'); }
	YY_BREAK
case 139:
{ count_output(); if (cover_all) return('-'); }
	YY_BREAK
case 140:
{ count_output(); if (cover_all) return('+'); }
	YY_BREAK
case 141:
{ count_output(); if (cover_all) return('*'); }
	YY_BREAK
case 142:
{ count_output(); if (cover_all) return('/'); }
	YY_BREAK
case 143:
{ count_output(); if (cover_all) return('%'); }
	YY_BREAK
case 144:
{ count_output(); if (cover_all) return('<'); }
	YY_BREAK
case 145:
{ count_output(); if (cover_all) return('>'); }
	YY_BREAK
case 146:
{ count_output(); if (cover_all) return('^'); }
	YY_BREAK
case 147:
{ count_output(); if (cover_all) return('|'); }
	YY_BREAK
case 148:
{ count_output(); if (cover_all) return('?'); }
	YY_BREAK
case 149:
{ count(); cover_output(' '); }
	YY_BREAK
case 150:
{ count(); }
	YY_BREAK
case 151:
{ count(); cover_output((int)(unsigned char)yytext[0]); }
	YY_BREAK
case 152:
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
    yyterminate();

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yytext - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yytext + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yytext + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yytext,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yytext + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yytext + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#ifdef FLEX_DEBUG
		printf( "action # %d\n", yy_act );
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH -
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    register YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yy_current_buffer->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp;

    yy_current_state = yy_start;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 532 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif

    {
    register int yy_is_jam;
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 532 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 531);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, register YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
register YY_CHAR *yy_bp;
#endif

    {
    register YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_CHAR *dest =
	    &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
	register YY_CHAR *source =
	    &yy_current_buffer->yy_ch_buf[number_to_move];

	while ( source > yy_current_buffer->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = yy_current_buffer->yy_buf_size;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yytext = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yytext + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;

#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yytext + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
	return;

    if ( yy_current_buffer )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
	}

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }


#ifndef FLEX
yywrap()
{
	return(1);
}
#endif

comment()
{
#ifdef FLEX
	fprintf(stderr,"\ncover: Input file contains a comment. Sorry, aborting...\n");
	exit(3);
#else
	char c, c1;

	ECHO;	/* leading "/*" */

loop:
	while ((c = input()) != '*' && c != 0)
		putc(c, yyout);

	putc(c, yyout);	/* the  '*' */

	if (c != 0 && (c1 = input()) != '/' && c1 != 0)
	{
		unput(c1);
		goto loop;
	}

	if (c != 0 && c1 != 0)
		putc(c1, yyout);
#endif
}

static void count_output(void)
{
        count();
        if (!cover_all) {
            fputs(yytext, yyout);
        }
}
